---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy
  labels:
    app: tinyproxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: tinyproxy
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      containers:
      - image: vimagick/tinyproxy
        name: tinyproxy
        resources: {}
        ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: tinyproxy
  labels:
    app: tinyproxy
spec:
  selector:
    app: tinyproxy
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888